"""Shared codegen helpers (SPEC.md sections 22-23, 29).

Hosts everything :mod:`src.codegen.rust` needs besides the function-body
emitter itself: the header and the amended byte-exact prelude, identifier
escaping and the type mapping table, literal rendering, AST traversal
utilities, the reserved-type-name renaming scheme, the ``PartialEq``
eq-reachability analysis (structs and enums), and struct/enum item
emission with the amended ``Debug, Clone`` derives.
"""

from __future__ import annotations

import math

from src.diagnostics import Span
from src.parser import ast
from src.sema.analyze import SemaResult
from src.sema.types import TCon

# --------------------------------------------------------------------- prelude

# Section 24: full output = header line + blank line + prelude + ... The
# SPEC pins the header line's existence (sections 23-24) but not its text.
# The header line doubles as an inner attribute: rustc const-evaluates
# constant `/ 0` and `% 0` under the deny-by-default unconditional_panic
# lint, which would reject accepted programs; the runtime panic is the
# semantically consistent outcome, so the lint is allowed file-wide.
HEADER = "#![allow(unconditional_panic)] // Generated by the Oxide transpiler."

# Section 23 as REPLACED by section 29: the original four functions
# verbatim, then the nine v0.2 builtins in pinned order, then the two
# section-37 (v0.2.1) additions in pinned order, then the five v0.4
# additions in pinned order (Task 3 census gate slate).
#
# Fix round (2026-08-28, dossier-4 builtin shadowing): kept as ``name ->
# fn-text`` pairs, not one flat string, so ``prelude_for`` can omit a
# builtin's own definition when a user ``fn`` of the same name shadows it
# program-wide -- resolve.py then routes every reachable call site to the
# user's fn (see ``resolve.py::_declare_name``/``_callee``), so keeping
# the builtin's prelude definition would only leave a dead, unreachable
# item that collides with the user's same-named fn as a duplicate
# top-level Rust definition (E0428). ``PRELUDE`` (the unfiltered/default
# case, no shadowing) is unchanged byte-for-byte from before this split.
_PRELUDE_HEADER = "#![allow(dead_code)]"

_PRELUDE_FNS: tuple[tuple[str, str], ...] = (
    (
        "print",
        'fn print<T: std::fmt::Debug>(x: &T) {\n    println!("{:?}", x);\n}',
    ),
    ("len", "fn len<T>(v: &Vec<T>) -> i64 {\n    v.len() as i64\n}"),
    (
        "push",
        "fn push<T>(mut v: Vec<T>, x: T) -> Vec<T> {\n"
        "    v.push(x);\n"
        "    v\n"
        "}",
    ),
    ("vec", "fn vec<T>() -> Vec<T> {\n    Vec::new()\n}"),
    ("clone", "fn clone<T: Clone>(x: &T) -> T {\n    x.clone()\n}"),
    (
        "get",
        "fn get<T: Clone>(v: &Vec<T>, i: i64) -> Option<T> {\n"
        "    if i < 0 {\n"
        "        return None;\n"
        "    }\n"
        "    v.get(i as usize).cloned()\n"
        "}",
    ),
    ("range", "fn range(a: i64, b: i64) -> Vec<i64> {\n    (a..b).collect()\n}"),
    (
        "print_str",
        'fn print_str(s: &String) {\n    println!("{}", s);\n}',
    ),
    (
        "str_len",
        "fn str_len(s: &String) -> i64 {\n    s.chars().count() as i64\n}",
    ),
    ("concat", "fn concat(a: String, b: String) -> String {\n    a + &b\n}"),
    (
        "chars",
        "fn chars(s: &String) -> Vec<String> {\n"
        "    s.chars().map(|c| c.to_string()).collect()\n"
        "}",
    ),
    (
        "int_to_str",
        "fn int_to_str(x: i64) -> String {\n    x.to_string()\n}",
    ),
    (
        "parse_int",
        "fn parse_int(s: &String) -> Option<i64> {\n"
        "    s.trim().parse::<i64>().ok()\n"
        "}",
    ),
    ("to_float", "fn to_float(x: i64) -> f64 {\n    x as f64\n}"),
    ("trunc", "fn trunc(x: f64) -> i64 {\n    x as i64\n}"),
    ("to_str", "fn to_str(x: i64) -> String {\n    x.to_string()\n}"),
    (
        "sort",
        "fn sort<T: Ord>(v: Vec<T>) -> Vec<T> {\n"
        "    let mut t = v;\n"
        "    t.sort();\n"
        "    t\n"
        "}",
    ),
    (
        "min",
        "fn min<T: Ord + Clone>(v: &Vec<T>) -> Option<T> {\n"
        "    v.iter().min().cloned()\n"
        "}",
    ),
    (
        "max",
        "fn max<T: Ord + Clone>(v: &Vec<T>) -> Option<T> {\n"
        "    v.iter().max().cloned()\n"
        "}",
    ),
    ("sum", "fn sum(v: &Vec<i64>) -> i64 {\n    v.iter().sum()\n}"),
    (
        "contains",
        "fn contains<T: PartialEq>(v: &Vec<T>, x: &T) -> bool {\n"
        "    v.contains(x)\n"
        "}",
    ),
    (
        "count",
        "fn count<T: PartialEq>(v: &Vec<T>, x: &T) -> i64 {\n"
        "    v.iter().filter(|e| *e == x).count() as i64\n"
        "}",
    ),
    (
        "unwrap_or",
        "fn unwrap_or<T>(o: Option<T>, d: T) -> T {\n"
        "    match o {\n"
        "        Some(x) => x,\n"
        "        None => d,\n"
        "    }\n"
        "}",
    ),
    (
        "count_if",
        "fn count_if<T>(v: &Vec<T>, p: impl Fn(&T) -> bool) -> i64 {\n"
        "    v.iter().filter(|e| p(e)).count() as i64\n"
        "}",
    ),
    # v0.4 wave-3: swap/reverse/set. Each takes the vector by value and
    # returns it, wrapping the in-place std method -- the owned-in/
    # owned-out convention `sort` established. Out-of-range indices panic
    # from Rust's own operations (SPEC 60.2).
    (
        "swap",
        "fn swap<T>(mut v: Vec<T>, i: i64, j: i64) -> Vec<T> {\n"
        "    v.swap(i as usize, j as usize);\n"
        "    v\n"
        "}",
    ),
    (
        "reverse",
        "fn reverse<T>(mut v: Vec<T>) -> Vec<T> {\n"
        "    v.reverse();\n"
        "    v\n"
        "}",
    ),
    (
        "set",
        "fn set<T>(mut v: Vec<T>, i: i64, x: T) -> Vec<T> {\n"
        "    v[i as usize] = x;\n"
        "    v\n"
        "}",
    ),
)


def prelude_for(shadowed: frozenset[str]) -> str:
    """The prelude with any builtin fn named in ``shadowed`` omitted.

    ``shadowed`` is empty in the overwhelmingly common case (no program
    defines a fn colliding with a builtin name), which reproduces
    ``PRELUDE`` exactly."""
    fns = [text for name, text in _PRELUDE_FNS if name not in shadowed]
    return _PRELUDE_HEADER + "\n\n" + "\n\n".join(fns)


PRELUDE = prelude_for(frozenset())

# --------------------------------------------------------------------- naming

TYPE_MAP = {"Int": "i64", "Float": "f64", "Bool": "bool", "Str": "String", "Unit": "()"}

# Rust keywords that are legal Oxide identifiers and must emit as r#name.
_RUST_KEYWORDS = frozenset(
    {
        "as", "break", "const", "continue", "enum", "extern", "for", "impl",
        "in", "loop", "mod", "move", "mut", "pub", "ref", "static", "trait",
        "type", "unsafe", "use", "where", "async", "await", "dyn", "abstract",
        "become", "box", "do", "final", "macro", "override", "priv", "typeof",
        "unsized", "virtual", "yield", "try", "gen", "union",
        # Oxide keywords can never be identifiers, but keep the set total.
        "else", "false", "fn", "if", "let", "match", "return", "struct",
        "true", "while",
    }
)

# These cannot be raw identifiers in Rust at all (`_` is a pattern, not
# an expression, and r#_ is invalid).
_UNRAWABLE = {
    "self": "__oxide_self",
    "Self": "__oxide_Self",
    "super": "__oxide_super",
    "crate": "__oxide_crate",
    "_": "__oxide_underscore",
}

# Type names the mapper emits; a user struct/enum with one of these names
# would shadow them, so such items are renamed (Vec/Option/Result are
# rejected by sema, listed for completeness).
_RESERVED_TYPE_NAMES = frozenset(
    {"String", "i64", "f64", "bool", "Vec", "Option", "Result"}
)

# Largest value rustc accepts for an unsuffixed literal in an
# i32-defaulted (unconstrained) position; bigger literals carry `i64`.
I32_MAX = 2**31 - 1

INDENT = "    "

# Binding powers matching SPEC.md section 10 (relative order identical in Rust).
PREC = {
    "||": 1,
    "&&": 2,
    "==": 3, "!=": 3, "<": 3, "<=": 3, ">": 3, ">=": 3,
    "+": 4, "-": 4,
    "*": 5, "/": 5, "%": 5,
}

EQ_OPS = frozenset({"==", "!="})

# The (non-associative) comparison tier of PREC.
CMP_PREC = PREC["=="]

# Ref-form argument positions per builtin (section 22 as extended by the
# section 29 prelude signatures): True where the prelude takes &T.
BUILTIN_REF: dict[str, tuple[bool, ...]] = {
    "print": (True,),
    "len": (True,),
    "push": (False, False),
    "vec": (),
    "clone": (True,),
    "get": (True, False),
    "range": (False, False),
    "print_str": (True,),
    "str_len": (True,),
    "concat": (False, False),
    "chars": (True,),
    "int_to_str": (False,),
    "parse_int": (True,),
    "to_float": (False,),
    "trunc": (False,),
    "to_str": (False,),
    # v0.4 (Task 3): sort takes Vec<T> by value (consuming, like push's `v`);
    # min/max/sum/contains take &Vec<T> (reading, like get/len); contains'
    # searched value is also a ref (mirrors clone's unconditional `&T`, not
    # push's owned value slot -- see the mode note on BUILTINS["contains"]).
    "sort": (False,),
    "min": (True,),
    "max": (True,),
    "sum": (True,),
    "contains": (True, True),
    # v0.4 wave-2 (Task 3): count mirrors contains exactly -- both slots
    # ref-form, same reading modes, same generic-T shape. Verified against
    # the prelude signature by probing rustc directly: `v.iter().filter(|e|
    # *e == x).count()` needs exactly one deref on the filter closure's
    # `&&T` item (`*e: &T`) to line up with `x: &T` via the stdlib's
    # `&A: PartialEq<&B> where A: PartialEq<B>` blanket impl -- `**e == x`
    # would compare `T` against `&T`, which does not typecheck generically.
    "count": (True, True),
    # v0.4 (Task 5): both slots are owned/by-value (no ref-form) -- matches
    # the "own" modes above, both args are moved into unwrap_or<T>.
    "unwrap_or": (False, False),
    # v0.4 wave-3 (Task 3): every slot by value -- the vector is consumed
    # (like `sort`), the indices are Copy i64, and `set`'s value is moved
    # in (like `push`'s inserted value). No slot takes ref-form.
    # count_if reads its vector (&Vec<T>, like contains) and takes the
    # predicate by value -- a predicate literal is not a place, it is
    # emitted inline as a Rust closure.
    "count_if": (True, False),
    "swap": (False, False, False),
    "reverse": (False,),
    "set": (False, False, False),
}


def escape(name: str) -> str:
    """Keyword-escape one identifier (section 22, Names)."""
    special = _UNRAWABLE.get(name)
    if special is not None:
        return special
    if name in _RUST_KEYWORDS:
        return f"r#{name}"
    return name


def rust_type(ty: object, renames: dict[str, str] | None = None) -> str:
    """Render a solved sema type as Rust (section 22 mapping table, with
    the builtin generic enums Option/Result mapped structurally)."""
    if isinstance(ty, TCon):
        base = TYPE_MAP.get(ty.name)
        if base is None:
            if renames is not None and ty.name in renames:
                base = renames[ty.name]
            else:
                base = escape(ty.name)
        if ty.args:
            args = ", ".join(rust_type(a, renames) for a in ty.args)
            return f"{base}<{args}>"
        return base
    raise ValueError(f"emit_rust: cannot map type {ty!r}")


def type_from_annotation(ty_expr: ast.TypeExpr) -> TCon:
    """Declared TypeExpr -> TCon (clean modules only name valid types)."""
    return TCon(ty_expr.name, tuple(type_from_annotation(a) for a in ty_expr.args))


def rust_string(value: str) -> str:
    """Escape an unescaped string value as a Rust string literal body."""
    out: list[str] = []
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\0":
            out.append("\\0")
        elif 32 <= ord(ch) < 127:
            out.append(ch)
        else:
            out.append(f"\\u{{{ord(ch):x}}}")
    return "".join(out)


def float_repr(value: float) -> str:
    if math.isinf(value):
        return "f64::INFINITY" if value > 0 else "f64::NEG_INFINITY"
    return repr(value)


def span_key(span: Span) -> tuple[int, int]:
    return (span.start, span.end)


# ------------------------------------------------------------------- traversal


def iter_nodes(root: object):
    """Yield ``root`` and every AST descendant (items, stmts, exprs)."""
    stack: list[object] = [root]
    while stack:
        node = stack.pop()
        yield node
        match node:
            case ast.Module(items=items):
                stack.extend(items)
            case ast.FnDecl(body=body):
                stack.append(body)
            case ast.Block(stmts=stmts, tail=tail):
                stack.extend(stmts)
                if tail is not None:
                    stack.append(tail)
            case ast.Let(init=init):
                stack.append(init)
            case ast.Assign(value=value):
                stack.append(value)
            case ast.FieldAssign(value=value):
                stack.append(value)
            case ast.Return(value=value):
                if value is not None:
                    stack.append(value)
            case ast.ExprStmt(expr=expr):
                stack.append(expr)
            case ast.While(cond=cond, body=body):
                stack.extend((cond, body))
            case ast.For(iterable=iterable, body=body):
                stack.extend((iterable, body))
            case ast.If(cond=cond, then_blk=then_blk, else_blk=else_blk):
                stack.extend((cond, then_blk))
                if else_blk is not None:
                    stack.append(else_blk)
            case ast.Match(scrutinee=scrutinee, arms=arms):
                stack.append(scrutinee)
                stack.extend(arm.body for arm in arms)
            case ast.Call(callee=callee, args=args):
                stack.append(callee)
                stack.extend(args)
            case ast.BinOp(lhs=lhs, rhs=rhs):
                stack.extend((lhs, rhs))
            case ast.UnOp(operand=operand):
                stack.append(operand)
            case ast.FieldAccess(obj=obj):
                stack.append(obj)
            case ast.StructLit(fields=fields, rest=rest):
                stack.extend(fexpr for _fname, fexpr in fields)
                if rest is not None:
                    stack.append(rest)
            case ast.Try(operand=operand):
                stack.append(operand)


def exposed_struct_lit(expr: object) -> bool:
    """True when a struct literal sits at an exposed (unparenthesized)
    position of a condition expression — Rust forbids struct literals
    there, so the emitted condition must be wrapped in parentheses."""
    match expr:
        case ast.StructLit():
            return True
        case ast.BinOp(lhs=lhs, rhs=rhs):
            return exposed_struct_lit(lhs) or exposed_struct_lit(rhs)
        case ast.UnOp(operand=operand):
            return exposed_struct_lit(operand)
        case ast.FieldAccess(obj=obj):
            return exposed_struct_lit(obj)
        case ast.Try(operand=operand):
            return exposed_struct_lit(operand)
    return False


# ------------------------------------------------------------ items & derives


def type_renames(module: ast.Module) -> dict[str, str]:
    """Emitted name per struct/enum: reserved Rust type names are bumped
    with the section-22 ``name__N`` scheme, skipping occupied names."""
    renames: dict[str, str] = {}
    used: set[str] = set()
    for item in module.items:
        if not isinstance(item, (ast.StructDecl, ast.EnumDecl)):
            continue
        candidate = escape(item.name)
        nth = 1
        while candidate in _RESERVED_TYPE_NAMES or candidate in used:
            nth += 1
            candidate = f"{item.name}__{nth}"
        used.add(candidate)
        renames[item.name] = candidate
    return renames


def eq_derive_types(res: SemaResult) -> frozenset[str]:
    """Struct/enum names needing ``PartialEq``: any user type reachable
    from the operand type of some ``==``/``!=`` (through Vec/Option/Result
    arguments, struct fields, and enum payloads)."""
    structs = res.resolve.structs
    enums = res.resolve.enums
    needed: set[str] = set()

    def visit_type(ty: object) -> None:
        if not isinstance(ty, TCon):
            return
        for arg in ty.args:
            visit_type(arg)
        visit_name(ty.name)

    def visit_name(name: str) -> None:
        if name in needed:
            return
        struct_decl = structs.get(name)
        if struct_decl is not None:
            needed.add(name)
            for field_def in struct_decl.fields:
                visit_type(type_from_annotation(field_def.ty))
            return
        enum_decl = enums.get(name)
        if enum_decl is not None:
            needed.add(name)
            for _vname, payload_tys in enum_decl.variants:
                for payload_ty in payload_tys:
                    visit_type(type_from_annotation(payload_ty))

    for node in iter_nodes(res.module):
        if isinstance(node, ast.BinOp) and node.op in EQ_OPS:
            visit_type(res.infer.types.get(node.lhs.node_id))
    return frozenset(needed)


def _derive_line(needs_eq: bool) -> str:
    # Section 29: structs AND enums derive (Debug, Clone); PartialEq is
    # added exactly when the program applies ==/!= to (a container of)
    # this type — without it the comparison would not compile (E0369).
    if needs_eq:
        return "#[derive(Debug, Clone, PartialEq)]"
    return "#[derive(Debug, Clone)]"


def emit_struct(
    decl: ast.StructDecl, renames: dict[str, str], needs_eq: bool
) -> str:
    name = renames.get(decl.name, escape(decl.name))
    header = f"{_derive_line(needs_eq)}\nstruct {name}"
    if not decl.fields:
        return header + " {}"
    lines = [header + " {"]
    for field_def in decl.fields:
        field_ty = rust_type(type_from_annotation(field_def.ty), renames)
        lines.append(f"{INDENT}{escape(field_def.name)}: {field_ty},")
    lines.append("}")
    return "\n".join(lines)


def emit_enum(
    decl: ast.EnumDecl, renames: dict[str, str], needs_eq: bool
) -> str:
    name = renames.get(decl.name, escape(decl.name))
    header = f"{_derive_line(needs_eq)}\nenum {name}"
    if not decl.variants:
        return header + " {}"
    lines = [header + " {"]
    for vname, payload_tys in decl.variants:
        if payload_tys:
            args = ", ".join(
                rust_type(type_from_annotation(t), renames) for t in payload_tys
            )
            lines.append(f"{INDENT}{escape(vname)}({args}),")
        else:
            lines.append(f"{INDENT}{escape(vname)},")
    lines.append("}")
    return "\n".join(lines)
